name: Scrape Cron

on:
  workflow_dispatch:
  schedule:
  #starts are every day at 6:30 and 17:30 UTC:
  - cron:  '30 6,17 * * *'
  push:
    branches:
    - master
    - main
    
jobs:
  build:
    name: Scrape Cron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
#      - name: Delete Old Files
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git rm ./data/countries/*.json
#                       
#      - name: commit deleted old files
#        uses: zwaldowski/git-commit-action@v1
#        with:
#             commit_message:  "deleted old files by bot"
#             working_directory: .
#           
#      - name: Push changes for old files
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.scrapper_token }}
#          branch: ${{ github.ref }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%Y-%m-%d')"

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: run
        run: go run .

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*
          git commit -m "cron: new data" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.scrapper_token }}
